#!/usr/bin/env python
import optparse
import sys
import models
import itertools, math
from collections import namedtuple, defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input", dest="input", default="data/input", help="File containing sentences to translate (default=data/input)")
optparser.add_option("-t", "--translation-model", dest="tm", default="data/tm", help="File containing translation model (default=data/tm)")
optparser.add_option("-l", "--language-model", dest="lm", default="data/lm", help="File containing ARPA-format language model (default=data/lm)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to decode (default=no limit)")
optparser.add_option("-k", "--translations-per-phrase", dest="k", default=1, type="int", help="Limit on number of translations to consider per phrase (default=1)")
optparser.add_option("-s", "--stack-size", dest="s", default=1, type="int", help="Maximum stack size (default=1)")
optparser.add_option("-v", "--verbose", dest="verbose", action="store_true", default=False,  help="Verbose mode (default=off)")
opts = optparser.parse_args()[0]

tm = models.TM(opts.tm, opts.k)
lm = models.LM(opts.lm)
french = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]
def extract_english(h): 
  return "" if h.predecessor is None else "%s%s " % (extract_english(h.predecessor), h.phrase.english)

# tm should translate unknown words as-is with probability 1
for word in set(sum(french,())):
  if (word,) not in tm:
    tm[(word,)] = [models.phrase(word, 0.0)]
max_perms = 100000
sys.stderr.write("Decoding %s...\n" % (opts.input,))
for french_sentence in french:
  hypothesis = namedtuple("hypothesis", "logprob, lm_state, predecessor, phrase")
  intial_hypothesis = hypothesis(0.0, lm.begin(), None, None)
  stacks = [{} for _ in french_sentence] + [{}]
  for i in xrange(0,len(french_sentence)+1):
    stacks[i][lm.begin()] = intial_hypothesis
  for i, stack in enumerate(stacks[:-1]):
    #sys.stderr.write("looking at stack %i\n" % i)
    for current_hypothesis in sorted(stack.itervalues(),key=lambda h: -h.logprob)[:opts.s]:
      iterator = 0
      for j, perm in enumerate(itertools.combinations(french_sentence,i+1)):
        if perm in tm:
          iterator += 1
          #sys.stderr.write("iteration %i\n" % iterator)
          for phrase in tm[perm]:
            logprob = current_hypothesis.logprob + phrase.logprob
            current_lm_state = current_hypothesis.lm_state
            for word in phrase.english.split():
              (current_lm_state, word_logprob) = lm.score(current_lm_state, word)
              logprob += word_logprob
            logprob += lm.end(current_lm_state) 
            new_hypothesis = hypothesis(logprob, current_lm_state, current_hypothesis, phrase)
            #sys.stderr.write(extract_english(new_hypothesis)+'\n')
            if current_lm_state not in stacks[i] or stacks[i][current_lm_state].logprob < logprob:
              stacks[i][current_lm_state] = new_hypothesis
          if iterator > max_perms:
            break

  winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
  #sys.stderr.write(extract_english(winner)+'\n')
  print extract_english(winner)

  if opts.verbose:
    def extract_tm_logprob(h):
      return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
    tm_logprob = extract_tm_logprob(winner)
    sys.stderr.write("LM = %f, TM = %f, Total = %f\n" %
                     (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
